### ISSUE TITLE
Flip the default column spacing for the name and path fields

### ISSUE THREAD

**Issue by alan-cugler** [OlavStornes/ModBuddy#13]
The `path` field is helpful when trying to remember where the source files are coming from, but most of the time this text is adding eye fatigue. it would be nice to make the path column toggle-able, and start out minimized (ex: "/path/to/f..."), and have the `name` column fully expanded as that is for informative when deciding which mods I am trying to use.

## Default
![image](https://user-images.githubusercontent.com/25991646/149678211-deefa885-6eb5-48d1-a015-d15940b4e296.png)

## Preferred
![image](https://user-images.githubusercontent.com/25991646/149678356-202c2629-4dbf-4508-a08d-fc9e038d7333.png)

**Comment by alan-cugler** [comment]
Being able to toggle the path column on and off entirely would be best, but I am assuming UI adjustments like that are difficult since every attempt at frontend causes me to be thankful I do only backend at work.
XD

**Comment by OlavStornes** [comment]
Good call. I've found a somewhat working solution to this. I've also stripped away a lot of information in the mod paths, so it should be much more tidier as of the latest commit.

(and yes, UI adjustments are a pain, especially when experimenting with Qt)
